function[Hd b a] = NotchIrFir100(Fs)  
if nargin<1
    Fs=input(' Enter sampling frequency ');
% else 
%     Fs=Fs;
end
%NOTCHIRFIR Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 14-May-2013 07:59:06
%

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
% Fs = 2400;  % Sampling Frequency

Fnotch = 100;  % Notch Frequency
BW     = 1;     % Bandwidth
Apass  = 1;     % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
