function list = loadListOfResults(project)

list = [];
switch lower(project)
    case 'bibliocampus'
        list = {'optogeneticResponse','averageCCG','ripples_psth','slowOscillations_psth','theta_*.PhaseLockingData','thetaREM*.PhaseLockingData',...
            'thetaRun*.PhaseLockingData','lgamma*.PhaseLockingData','hgamma*.PhaseLockingData','ripple*.PhaseLockingData','spatialModulation','placeFields','behavior.cellinfo','ACGPeak',...
            'speedCorr','uLEDResponse.cellinfo'};


    case 'lightininh'
       list = {'optogeneticResponse','averageCCG','ripples_psth','slowOscillations_psth','theta_*.PhaseLockingData','thetaREM*.PhaseLockingData',...
        'thetaRun*.PhaseLockingData','lgamma*.PhaseLockingData','hgamma*.PhaseLockingData','ripple*.PhaseLockingData','spatialModulation','placeFields','behavior.cellinfo','ACGPeak',...
        'speedCorr.cellinfo','uLEDResponse.cellinfo','lightSpikeCollisions','spikeCCGchange','lightSpikeCollisions_pre','lightSpikeCollisions_post','ripplespsthRipples_before',...
        'ripplespsthRipples_after','cell_metrics_after','cell_metrics_before','mono_res.cellinfo','mono_res_after.cellinfo', 'mono_res_before.cellinfo'};


    % case 'lightininh'
    %    list = {'optogeneticResponse','averageCCG','ripples_psth','slowOscillations_psth','theta_*.PhaseLockingData','thetaREM*.PhaseLockingData',...
    %     'thetaRun*.PhaseLockingData','lgamma*.PhaseLockingData','hgamma*.PhaseLockingData','ripple*.PhaseLockingData','spatialModulation','placeFields','behavior.cellinfo','ACGPeak',...
    %     'speedCorr.cellinfo','uLEDResponse.cellinfo','lightSpikeCollisions','spikeCCGchange','lightSpikeCollisions_pre','lightSpikeCollisions_post','ripplespsthRipples_before',...
    %     'ripplespsthRipples_after','mono_res.cellinfo'};


    case 'potometry'
        list = {'fiber_psth_ripples','fiber_psth_ripples_PreSleep2','fiber_psth_ripples_PostSleep2','FiberPhotometry','ripples_psth.cellinfo', 'SessionArmChoice.Events','behavior','behavior_fiber',...
            'peri_spike_trace_PreSleep2','peri_spike_trace_PostSleep2'};
        
    otherwise
        list = {'optogeneticResponse','ripples_psth','slowOscillations_psth','theta_*.PhaseLockingData','lgamma*.PhaseLockingData','hgamma*.PhaseLockingData','ripple*.PhaseLockingData',...
            'spatialModulation','placeFields','behavior.cellinfo','ACGPeak'};
end 
end